### PR TITLE
Bug: Fix Filter Panel's search by name

### LINKED ISSUE #226: Find Command: Name matching is not functioning properly
The 'Search by Name' is not functioning properly as it is unable to parse names correctly.

The error lies in the `PersonMatchesDetailsPredicate` due to an artefact from an uncaught bug from #202, as the old name matching method is still being used instead of the updated one.

### PR DESCRIPTION
**Pull request by dinhcodes**
* Fixes #226 
### Bug:
* The 'Search by Name' is not functioning properly as it is unable to parse names correctly.
* The error lies in the PersonMatchesDetailsPredicate due to an artefact from an uncaught bug from https://github.com/AY2526S2-CS2103T-T15-1/tp/pull/202, as the old name matching method is still being used instead of the updated one.

### Fix:
* Update name logic to use fuzzyMatches like the rest of the fields

### CODE REVIEW

File: src/main/java/seedu/address/model/person/PersonMatchesDetailsPredicate.java [hunk 1]
```diff
@@ -31,7 +30,7 @@ public FilterDetails filterDetails() {
 
     @Override
     public boolean test(Person person) {
-        return isNameMatch(person)
+        return isFuzzyMatch(person.getName().fullName, filterDetails.getNameKeywords())
```
Comment (ananyaj1515) [inline src/main/java/seedu/address/model/person/PersonMatchesDetailsPredicate.java]: Thanks for catching and fixing this!
